# Generated by Django 3.2.7 on 2021-10-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название направления', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название курса', max_length=30)),
                ('num', models.IntegerField(help_text='Введите количество занятий')),
                ('time', models.IntegerField(help_text='Введите время одного занятия')),
                ('days', models.CharField(help_text='Введите дни недели когда будут проходить занятия (через запятую)', max_length=100)),
                ('firstdate', models.DateField(help_text='Введите дату первого занятия')),
                ('lastdate', models.DateField(help_text='Введите дату последнего занятия')),
                ('price', models.IntegerField(help_text='Введите стоимость курса')),
                ('info', models.TextField(help_text='Введите подробную информацию про курс')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.direction')),
            ],
        ),
    ]
