# Generated by Django 3.2.7 on 2021-10-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_name_direction_название'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='Название',
            new_name='name',
        ),
    ]
