# Generated by Django 3.2.7 on 2021-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_название_direction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=20)),
                ('surname', models.CharField(help_text='Фамилия', max_length=30)),
                ('fathername', models.CharField(help_text='Отчество', max_length=30)),
                ('email', models.EmailField(help_text='Электронная почта', max_length=254)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=12)),
                ('comment', models.TextField(help_text='Комментарий', null=True)),
                ('pay', models.BooleanField(default=False, help_text='Есть ли оплата')),
                ('dateofpay', models.DateField(help_text='Дата оплаты', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(help_text='Дни недели когда будут проходить занятия (через запятую)', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='firstdate',
            field=models.DateField(help_text='Дата первого занятия'),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(help_text='Подробная информацая про курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lastdate',
            field=models.DateField(help_text='Дата последнего занятия'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Название курса', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='num',
            field=models.IntegerField(help_text='Количество занятий'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(help_text='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(help_text='Время одного занятия'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(help_text='Название направления', max_length=30),
        ),
    ]
