# Generated by Django 3.2.7 on 2021-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211025_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateofpay',
            field=models.DateField(blank=True, help_text='Дата оплаты', null=True),
        ),
    ]
