# Generated by Django 3.2.7 on 2021-11-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_person_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dateofpay',
            field=models.DateField(help_text='Дата оплаты', null=True),
        ),
    ]
